services:
  # Chess AI Backend
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: chess-ai-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - chess-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: chess-ai-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - chess-network
    restart: unless-stopped

networks:
  chess-network:
    driver: bridge